services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - demo-graphql-nodejs
    env_file:
      - .env
    depends_on:
      - db
    command: npm run start

  db:
    image: yobasystems/alpine-mariadb
    hostname: mariadb-graphql-nodejs
    networks:
      - demo-graphql-nodejs
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: graphql_nodejs
      MYSQL_USER: usuario
      MYSQL_PASSWORD: secr3t
    volumes:
      - ./base-datos/db-data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  demo-graphql-nodejs:
    driver: bridge
